export const TO_WX_LOGIN = 'TO_WX_LOGIN';
export const TO_PHONE_LOGIN = 'TO_PHONE_LOGIN';
export const CHANGE_NICKNAME = 'CHANGE_NICKNAME';
export const UPLOAD_USER_PIC = 'UPLOAD_USER_PIC'; 
export const DEL_PHONE_LOGIN = 'DEL_PHONE_LOGIN';
export const WX_SET_POSITION = 'WX_SET_POSITION';
export const WX_SET_POSITION_NAME = 'WX_SET_POSITION_NAME';
export const SET_AUTHORIZATION = 'SET_AUTHORIZATION';
export const SEND_ORDER_INFO = 'SEND_ORDER_INFO';
export const EDIT_ADDRESS_INFO = 'EDIT_ADDRESS_INFO';
export const INIT_ADD_ADDRESS = 'INIT_ADD_ADDRESS';
export const CHANGE_CHANGE_LOCATION = 'CHANGE_CHANGE_LOCATION';
export const GET_MAP_NEARBY_LIST = 'GET_MAP_NEARBY_LIST';
export const SET_CLASSIFY = 'SET_CLASSIFY';
export const CHANGE_WX_CITY = 'CHANGE_WX_CITY';
export const SETIPHONEX = 'SETIPHONEX';
export const ADD_ADDRESS_HISTORY = 'ADD_ADDRESS_HISTORY';

